[workspace]
default-members = ["crates/edit-ng"]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/armaans/edit-ng"
rust-version = "1.97.1"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"

[profile.dev]
opt-level = 1
debug = true
